### ISSUE TITLE
Вопросики и недочеты

### ISSUE THREAD

**Issue by fstr52** [Ne-pr1dumal/Calculation-Service-Yandex#1]
# Недочеты
1. А что с пакетом?
![image](https://github.com/user-attachments/assets/6a33e730-c8eb-4de5-ab83-151271da7766)
# Вопросы
И что, прям сам делал? Без нейронки?)

**Comment by Ne-pr1dumal** [comment]
**<А что с пакетом?>**
Забыл переименовать при импорте

**<И что, прям сам делал? Без нейронки?)>**
Мне лень сгружать тебе всю историю забросов, начиная от обратной польской записи, заканчивая вопросами про http-сервер
